import assert from 'node:assert/strict';
import test from 'node:test';

import { isAbsoluteWindowsPath, requestBrowserLensCapture } from './public/app/file-capability-panel.js';

test('file capability accepts drive and UNC paths but rejects web and relative targets', () => {
  assert.equal(isAbsoluteWindowsPath('C:\\Users\\me\\file.txt'), true);
  assert.equal(isAbsoluteWindowsPath('D:/School/model.dwg'), true);
  assert.equal(isAbsoluteWindowsPath('\\\\server\\share\\file.pdf'), true);
  assert.equal(isAbsoluteWindowsPath('https://example.com/file.pdf'), false);
  assert.equal(isAbsoluteWindowsPath('relative\\file.txt'), false);
  assert.equal(isAbsoluteWindowsPath(''), false);
});

test('Lens requests a real screen-region capture for the current browser tab', async () => {
  const calls = [];
  const expected = { ok: true, tab: { tabId: 'target-tab', url: 'https://www.google.com/search?udm=26' } };
  const host = {
    async fileCapability(operation, params) {
      calls.push({ operation, params });
      return expected;
    },
  };
  assert.equal(await requestBrowserLensCapture(host, 'source-tab', 'target-tab'), expected);
  assert.deepEqual(calls, [{
    operation: 'browser-lens-screen',
    params: { sourceTabId: 'source-tab', targetTabId: 'target-tab' },
  }]);
  assert.deepEqual(await requestBrowserLensCapture(host, '', 'target-tab'), { ok: false, error: 'Browser tab is unavailable.' });
});

test('file preview is a collapsed/expanded dock with a draggable width and no fake file-manager UI', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await readFile(new URL('./public/app/file-capability-panel.js', import.meta.url), 'utf8');
  const css = await readFile(new URL('./public/styles/file-capability.css', import.meta.url), 'utf8');
  const workspace = await readFile(new URL('./public/workspace-20260730b.js', import.meta.url), 'utf8');
  const html = await readFile(new URL('./public/workspace-20260730b.html', import.meta.url), 'utf8');
  const proximaPreviewHtml = await readFile(new URL('./public/proxima-preview.html', import.meta.url), 'utf8');
  const navigator = await readFile(new URL('./public/app/workspace-navigator.js', import.meta.url), 'utf8');
  const navigatorCss = await readFile(new URL('./public/styles/navigator.css', import.meta.url), 'utf8');
  const dropController = await readFile(new URL('./public/app/interactions/drop-controller.js', import.meta.url), 'utf8');
  const workspaceCommands = await readFile(new URL('./public/app/workspace-commands.js', import.meta.url), 'utf8');

  assert.doesNotMatch(source, /setOpen\(/, 'selection must never open/reposition a panel during pointerdown');
  assert.doesNotMatch(source, /file-capability-launcher/, 'the old floating launcher is gone');
  assert.match(source, /panel\.append\(resizer, header, body\)/);
  assert.match(source, /inspector\.append\(itemTitle, itemMeta, pathRow, preview\)/);
  assert.match(source, /file-capability-resizer/);
  assert.match(source, /setPointerCapture/);
  assert.match(source, /setPanelWidth\(viewportWidth - event\.clientX - 8\)/);
  assert.match(source, /setButtonSvg\(documentRef, copyPathButton, 'Copy path'/);
  assert.match(source, /setButtonSvg\(documentRef, revealButton, 'Reveal in file manager'/);
  assert.match(source, /No visual preview available yet\./);
  assert.match(source, /Folder navigation stays in your file manager\./);
  assert.match(source, /Multiple preview will take shape here\./);
  assert.match(css, /\.file-capability-panel \{[\s\S]*width: 38px/);
  assert.match(css, /\.file-capability-panel\.expanded \{[\s\S]*bottom: 8px[\s\S]*var\(--file-capability-width/);
  assert.match(css, /\.file-capability-panel \{[\s\S]*bottom: auto/);
  assert.match(css, /\.workspace\.file-capability-docked \.explorer \{[\s\S]*right: 0/);
  assert.match(css, /file-capability-expanded \.explorer \{[\s\S]*right: calc\(var\(--file-capability-width/);
  assert.match(workspace, /mode: 'single'/);
  assert.match(workspace, /mode: 'multiple'/);
  assert.match(html, /img-src 'self' data: blob: papers-file-preview: https: http:/);
  assert.match(html, /media-src papers-file-preview: blob:/);
  assert.match(html, /frame-src papers-file-preview: blob:/);
  assert.match(html, /style-src 'self' 'unsafe-inline'/);
  assert.match(proximaPreviewHtml, /style-src 'self' 'unsafe-inline'/);
  assert.match(html, /id="workspace-navigator"/);
  assert.match(html, /id="parent-graph-toggle"/);
  assert.match(navigator, /fileCapability\('list'/);
  assert.match(navigator, /fileCapability\('copy'/);
  assert.match(navigator, /fileCapability\('move'/);
  assert.match(navigator, /fileCapability\('rename'/);
  assert.match(navigator, /fileCapability\('delete'/);
  assert.match(navigator, /clearCanvasForMachine/);
  assert.match(navigator, /previewMachinePath/);
  assert.match(navigator, /workspace-navigator-view-toggle/);
  assert.match(navigator, /workspace-navigator-resizer/);
  assert.match(navigator, /head\.append\(provider, tools, viewToggle, collapse\)/);
  assert.match(navigator, /panel\.replaceChildren\(head,search,loc,body,resizer\)/);
  assert.doesNotMatch(navigator, /panel\.replaceChildren\(head,tools,search/);
  assert.match(navigator, /const move = button\(d,'Move',\['M4 2\.5h7l3 3v12H4z','M11 2\.5v4h4','M8 11h8','M13 8l3 3-3 3'\]\)/);
  assert.doesNotMatch(navigator, /Filters: ext:/);
  assert.match(navigatorCss, /\.workspace-navigator-search-info:empty\{display:none\}/);
  assert.match(navigator, /machineSort: \{ key:'name', direction:1 \}/);
  assert.match(navigator, /function machineColumnHeader\(\)/);
  assert.match(navigator, /\['name','Name'\],\['type','Type'\],\['size','Size'\],\['modified','Date Modified'\]/);
  assert.match(navigator, /function sortedMachineItems\(items\)/);
  assert.match(navigator, /a\.kind === 'folder' && b\.kind !== 'folder'/);
  assert.match(navigator, /function machinePathCrumbs\(path\)/);
  assert.match(navigator, /const driveRoot = `\$\{drive\[0\]\}\\\\`/);
  assert.match(navigator, /const shareRoot = `\\\\\\\\\$\{unc\[1\]\}\\\\\$\{unc\[2\]\}`/);
  assert.match(navigator, /const p=parentPath\(s\.path\);if\(p&&p\.toLocaleLowerCase\(\)!==s\.path\.toLocaleLowerCase\(\)\)void loadMachine\(p,true\)/);
  assert.doesNotMatch(navigator, /parentPath\(s\.path\)[^\n]*startsWith\(s\.machineRoot/);
  assert.match(navigator, /row\.addEventListener\('dblclick',[\s\S]*if\(folder\)[\s\S]*loadMachine\(x\.path,true\)/);
  assert.match(navigator, /row\.addEventListener\('dblclick',[\s\S]*fileCapability\('open',\{path:x\.path\}\)/);
  assert.match(navigatorCss, /\.workspace-navigator-machine-columns/);
  assert.match(navigatorCss, /\.workspace-navigator-row\.machine-list-row/);
  assert.match(navigator, /fileCapability\('icon'/);
  assert.match(navigator, /fileCapability\('search',\{query:normalized,limit:1000\}\)/);
  assert.match(navigator, /searchResult\.total/);
  assert.match(navigator, /formatSearchSize/);
  assert.match(navigator, /formatSearchDate/);
  assert.match(navigator, /searchFilters/);
  assert.match(navigator, /searchColumnHeader/);
  assert.match(navigator, /parseSizeFilter/);
  assert.match(navigator, /No results match these column filters/);
  assert.match(navigatorCss, /\.workspace-navigator-search-columns/);
  assert.match(navigatorCss, /grid-template-columns:24px minmax\(150px,1\.15fr\)/);
  assert.match(navigator, /pickTarget\('folder'\)/);
  assert.match(navigator, /papers:ayg:navigator-machine-root/);
  assert.match(navigator, /row\.draggable = true/);
  assert.match(navigator, /beginNavigatorNativeDrag/);
  assert.match(navigator, /event\.preventDefault\(\)/);
  assert.match(navigator, /fileCapability\?\.\('native-drag', \{ paths: unique \}\)/);
  assert.match(navigator, /nativeDragPaths/);
  assert.match(navigatorCss, /\.workspace-navigator-search/);
  assert.match(dropController, /application\/x-papers-native-items/);
  assert.match(dropController, /commands\.dropResolvedTargets/);
  assert.match(workspaceCommands, /async function dropResolvedTargets/);
  assert.match(workspaceCommands, /createDroppedShortcuts\(before, targets, normalizedDestination\)/);
  assert.match(navigator, /IntersectionObserver/);
  assert.match(navigator, /event\.shiftKey|e\.shiftKey/);
  assert.match(navigator, /contextmenu/);
  assert.match(navigator, /workspace-navigator-view-toggle/);
  assert.match(navigator, /scrollBy\(\{ left: delta, behavior: 'smooth' \}\)/);
  assert.match(navigator, /loc\.scrollLeft = loc\.scrollWidth/);
  assert.match(navigator, /navigator-collapsed/);
  assert.match(
    navigator,
    /selection\?\.mode === 'empty' && selection\.selectionCount === 0[\s\S]*if \(s\.mode === 'ayg'\) render\(\);[\s\S]*return;/,
    'clearing the AYG canvas selection must not eject an active external-folder navigator',
  );
  assert.doesNotMatch(navigator, /s\.ignore/, 'machine mode must not depend on consuming one lucky selection-sync event');
  assert.match(workspace, /workspaceNavigator\?\.isMachineMode\?\.\(\)/);
  assert.match(
    workspace,
    /selection\.mode === 'empty'[\s\S]*selection\.selectionCount === 0[\s\S]*return;/,
    'an empty AYG selection must not blank a preview currently owned by external-folder navigation',
  );
  assert.match(navigatorCss, /\.workspace-navigator/);
  assert.doesNotMatch(
    navigatorCss,
    /\.workspace\.navigator-docked \.explorer\s*\{[^}]*left:/,
    'the left navigator must overlay the workspace instead of shrinking/pushing the explorer frame',
  );
  assert.match(navigatorCss, /workspace-navigator-effective-width/);
  assert.match(navigatorCss, /\.workspace-navigator-resizer/);
  assert.match(navigatorCss, /\.workspace-navigator\.collapsed\{[^}]*width:34px[^}]*height:34px[^}]*background:transparent/);
  assert.match(navigator, /M8\.5 3\.5a5 5 0 1 0 0 10a5 5 0 1 0 0-10/);
  assert.doesNotMatch(navigator, /title\.textContent = 'Navigator'/);
  assert.match(navigatorCss, /overflow-x:auto/);
  assert.match(navigatorCss, /\.workspace-navigator-location-track/);
  assert.match(navigatorCss, /\.parent-graph-toggle/);
  assert.match(workspace, /parentGraphVisible !== false/);
});

test('file capability panel source keeps destructive retargeting verification-bound', async () => {
  const { readFile } = await import('node:fs/promises');
  const source = await readFile(new URL('./public/app/file-capability-panel.js', import.meta.url), 'utf8');
  const css = await readFile(new URL('./public/styles/file-capability.css', import.meta.url), 'utf8');
  const workspace = await readFile(new URL('./public/workspace-20260730b.js', import.meta.url), 'utf8');
  const navigator = await readFile(new URL('./public/app/workspace-navigator.js', import.meta.url), 'utf8');
  const navigatorCss = await readFile(new URL('./public/styles/navigator.css', import.meta.url), 'utf8');
  assert.match(source, /waitForPathState\(host, \{ present: expectedPath, absent: oldPath \}\)/);
  assert.match(source, /retargetShortcut\(\{[\s\S]*oldPath,[\s\S]*newPath: expectedPath/);
  assert.match(source, /fileCapability\('delete', \{ paths: \[target\] \}\)/);
  assert.match(source, /Moved to Recycle Bin\. The AYG reference was kept\./);
  assert.match(source, /URL\.createObjectURL\(new Blob/);
  assert.match(source, /URL\.revokeObjectURL\(state\.previewObjectUrl\)/);
  assert.match(source, /fileCapability\('preview-release', \{ resourceId \}\)/);
  assert.match(source, /parsed\.protocol === 'papers-file-preview:'/);
  assert.match(source, /fileCapability\('preview-text-chunk'/);
  assert.match(source, /media\.preload = 'metadata'/);
  assert.match(source, /fileCapability\('preview-native-open'/);
  assert.match(source, /fileCapability\('preview-native-move'/);
  assert.match(source, /fileCapability\('preview-native-close'/);
  assert.match(source, /data\.kind === 'hosted-pdf'/);
  assert.match(source, /fileCapability\('preview-pdf-open'/);
  assert.match(source, /fileCapability\('preview-pdf-move'/);
  assert.match(source, /fileCapability\('preview-pdf-close'/);
  assert.match(source, /data\.kind === 'hosted-html'/);
  assert.match(source, /fileCapability\('preview-html-open'/);
  assert.match(source, /fileCapability\('preview-html-move'/);
  assert.match(source, /fileCapability\('preview-html-close'/);
  assert.doesNotMatch(source, /fileCapability\('browser-open'/,
    'AYG web links must use durable browser tabs instead of the disposable preview lease');
  assert.match(source, /BROWSER_TABS_STORAGE_PREFIX/);
  assert.match(source, /const DEFAULT_BROWSER_HOME = 'https:\/\/www\.google\.com\/'/);
  assert.match(source, /const DEFAULT_SEARCH_URL = 'https:\/\/www\.google\.com\/search\?q='/);
  assert.doesNotMatch(source, /GOOGLE_LENS_HOME/);
  assert.match(source, /requestBrowserLensCapture\(host, sourceTab\.id, targetTabId\)/);
  assert.match(source, /fileCapability\('browser-lens-screen', \{ sourceTabId, targetTabId \}\)/);
  assert.match(source, /state\.browserTabs\.push\(\{[\s\S]*id: targetTabId/);
  assert.match(source, /fileCapability\('browser-downloads'/);
  assert.match(source, /fileCapability\('browser-download-bubble-show'/);
  assert.match(source, /fileCapability\('browser-download-bubble-hide'/);
  assert.match(source, /file-capability-browser-download-pie/);
  assert.match(source, /browserDownloadCompletionPending/);
  assert.doesNotMatch(source, /browserDownloadCompletionUntil/);
  assert.match(source, /if \(started\) state\.browserDownloadCompletionPending = false/);
  assert.match(source, /if \(completed\) state\.browserDownloadCompletionPending = true/);
  assert.match(source, /downloads\.addEventListener\('mouseenter',[\s\S]*browserDownloadCompletionPending = false/);
  assert.match(source, /downloads\.addEventListener\('click',[\s\S]*browserDownloadCompletionPending = false/);
  assert.match(source, /downloadProgress\(/);
  assert.match(source, /browserDownloadsOpen/);
  assert.match(source, /populateDownloadsPage\(/);
  assert.match(source, /surface\.classList\.add\('file-capability-browser-downloads-page'\)/);
  assert.doesNotMatch(source, /downloadsMenu/);
  assert.doesNotMatch(source, /file-capability-browser-downloads-heading/);
  assert.match(source, /fileCapability\('browser-adblock-state'/);
  assert.match(source, /fileCapability\('browser-adblock-set'/);
  assert.match(source, /function syncAdblockButton\(/);
  assert.match(source, /fileCapability\('open', \{ path: download\.path \}\)/);
  assert.match(source, /fileCapability\('reveal', \{ path: download\.path \}\)/);
  assert.match(source, /row\.draggable = draggable/);
  assert.match(source, /application\/x-papers-native-items/);
  assert.match(source, /fileCapability\('native-drag', \{ paths: \[download\.path\] \}\)/);
  assert.match(source, /download\.state === 'completed' && isAbsoluteWindowsPath\(download\.path\)/);
  assert.match(css, /\.file-capability-browser-downloads-page/);
  assert.match(css, /\.file-capability-browser-download-button\.downloading/);
  assert.match(css, /\.file-capability-browser-download-pie/);
  assert.match(css, /conic-gradient/);
  assert.match(css, /file-capability-download-complete/);
  assert.match(css, /\.file-capability-browser-download\[draggable="true"\]/);
  assert.doesNotMatch(css, /\.file-capability-browser-downloads-heading/);
  assert.doesNotMatch(css, /\.file-capability-browser-downloads \{/);
  assert.match(css, /\.file-capability-browser-adblock\.active/);
  assert.match(source, /createBrowserTab\(DEFAULT_BROWSER_HOME, \{ title: 'Google' \}\)/);
  assert.match(source, /DEFAULT_SEARCH_URL \+ encodeURIComponent\(input\)/);
  assert.match(source, /fileCapability\('browser-tab-open'/);
  assert.match(source, /fileCapability\('browser-tab-open-requests'/);
  assert.match(source, /function createBrowserTab\(url, \{ title = '', sourceKey = null, activate = true \} = \{\}\)/);
  assert.match(source, /if \(activate\) state\.activeBrowserTabId = tab\.id/);
  assert.match(source, /async function adoptBrowserOpenRequests\(requests\)/);
  assert.match(source, /activate: request\?\.activate !== false|const activate = request\?\.activate !== false/);
  assert.match(source, /browser-tab-open', \{[\s\S]*activate,/);
  assert.match(source, /fileCapability\('browser-tab-navigate'/);
  assert.match(source, /fileCapability\('browser-tab-command'/);
  assert.match(source, /fileCapability\('browser-tab-state'/);
  assert.match(source, /fileCapability\('browser-tab-move'/);
  assert.match(source, /fileCapability\('browser-tab-close'/);
  assert.match(source, /fileCapability\('browser-tabs-visible'/);
  assert.match(source, /function renderBrowserWorkspace\(\)/);
  assert.match(source, /windowRef\?\.localStorage\?\.setItem\(browserStorageKey/);
  assert.match(css, /\.file-capability-browser-shell/);
  assert.match(css, /\.file-capability-browser-tabs/);
  assert.match(css, /\.file-capability-browser-toolbar/);
  assert.match(css, /\.file-capability-browser-address/);
  assert.match(source, /inspector\.classList\.add\('browser-mode'\)/);
  assert.match(source, /inspector\.classList\.remove\('browser-mode'\)/);
  assert.match(source, /panel\.classList\.add\('browser-mode'\)/);
  assert.match(source, /panel\.classList\.remove\('browser-mode'\)/);
  assert.match(css, /\.file-capability-inspector\.browser-mode[\s\S]*padding: 0[\s\S]*gap: 0/);
  assert.match(css, /\.file-capability-inspector\.browser-mode > \.file-capability-item-title/);
  assert.match(css, /\.file-capability-panel\.expanded\.browser-mode[\s\S]*grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(css, /\.file-capability-panel\.expanded\.browser-mode \.file-capability-header[\s\S]*position: absolute/);
  assert.match(source, /host\.openNewSurface\(next\.toString\(\)\)/);
  assert.match(source, /FULL_PAGE_PREVIEW_STORAGE_PREFIX/);
  assert.match(source, /fileCapability\('preview-launch-create', payload\)/);
  assert.match(source, /fileCapability\('preview-launch-resolve', \{ token: launchToken \}\)/);
  assert.match(source, /fileCapability\('preview-markdown-obsidian', \{ path: target \}\)/);
  assert.match(source, /renderObsidianMarkdown/);
  assert.match(source, /class="markdown-reading-view"/);
  assert.match(source, /previewClass/);
  assert.match(source, /sandbox', 'allow-same-origin'/);
  assert.match(source, /child\.addEventListener\('wheel'/);
  assert.match(source, /event\.ctrlKey/);
  assert.match(source, /child\.documentElement\.style\.zoom/);
  assert.match(source, /preview\.scrollTop \+= event\.deltaY/);
  assert.match(source, /event\.button === 1/);
  assert.match(source, /papers-markdown-autoscroll-indicator/);
  assert.match(source, /requestAnimationFrame\?\.\(tickAutoscroll\)/);
  assert.match(source, /preview\.scrollBy\(/);
  assert.match(source, /ResizeObserver\(resizeToContent\)/);
  assert.match(css, /\.file-capability-obsidian-markdown/);
  assert.match(source, /fullPage: Boolean\(launchedPreview \|\| launchToken\)/);
  assert.match(source, /workspaceTitle: documentRef\.title/);
  assert.match(source, /workspaceIcon: documentRef\.head\.querySelector\('link\[data-papers-tab-icon\]'/);
  assert.match(source, /fileCapability\('icon', \{ path: state\.inspectedPath \}\)/);
  assert.match(source, /previewIcon: iconResult\?\.ok/);
  assert.match(workspace, /function syncWorkspaceTabIdentity\(\)/);
  assert.match(workspace, /const previewTitle = typeof parsed\?\.name === 'string'/);
  assert.match(workspace, /const title = previewTitle \|\| workspaceTitle/);
  assert.match(workspace, /const icon = previewIcon \|\| workspaceIcon/);
  assert.match(workspace, /title = current\?\.name \|\| scopedRoot\?\.name \|\| 'Workspace'/);
  assert.match(workspace, /data-papers-tab-icon/);
  assert.match(workspace, /FULL_PAGE_TAB_IDENTITY/);
  assert.match(source, /renderImagePreview\(source\)/);
  assert.match(source, /Zoom out/);
  assert.match(source, /Zoom in/);
  assert.match(source, /Fit image to preview/);
  assert.match(source, /viewport\.addEventListener\('wheel'/);
  assert.doesNotMatch(source, /if \(!event\.ctrlKey\) return/);
  assert.match(source, /viewport\.addEventListener\('pointerdown'/);
  assert.match(source, /viewport\.scrollLeft = pan\.scrollLeft - \(event\.clientX - pan\.x\)/);
  assert.match(source, /papers-embedded-surface/);
  assert.match(source, /previewStateKey/);
  assert.match(source, /ResizeObserver/);
  assert.match(css, /\.file-capability-image-toolbar/);
  assert.match(css, /\.file-capability-panel\.full-page/);
  assert.match(css, /\.file-capability-panel\.expanded \{[\s\S]*grid-template-rows: minmax\(0, 1fr\)/);
  assert.match(css, /\.file-capability-panel\.expanded \.file-capability-header \{[\s\S]*position: absolute[\s\S]*border: 0/);
  assert.match(css, /\.file-capability-panel\.expanded \.file-capability-body \{[\s\S]*grid-row: 1/);
  assert.match(css, /\.file-capability-panel\.embedded-surface-proxima/);
  assert.match(css, /\.file-capability-image-viewport\.panning/);
  const sidecarHtml = await readFile(new URL('./public/proxima-preview.html', import.meta.url), 'utf8');
  const sidecarCss = await readFile(new URL('./public/styles/proxima-preview-sidecar.css', import.meta.url), 'utf8');
  assert.match(sidecarHtml, /data-theme="dark"/);
  assert.match(sidecarCss, /--surface:\s*#272c37/);
  assert.match(css, /\.file-capability-text-scroller/);
  assert.match(css, /scrollbar-color: var\(--border-strong\) transparent/);
  assert.match(css, /::-webkit-scrollbar-thumb/);
  assert.match(navigatorCss, /workspace-navigator-body::-webkit-scrollbar-thumb/);
  assert.match(navigator, /isCollapsed: \(\) => s\.collapsed/);
  assert.match(navigator, /setCollapsed/);
  assert.match(source, /setExpanded: setExpandedWithPreviewLifecycle/);
  assert.doesNotMatch(source, /title\.textContent = 'Preview'/);
  assert.match(source, /setButtonSvg\(documentRef, expandButton, 'Expand file preview'/);
  assert.doesNotMatch(css, /file-capability-expand::before/);
  assert.match(source, /isFullPage: \(\) => state\.fullPage/);
  assert.match(workspace, /toggleSidePanes:[\s\S]*fileCapabilityPanel\.isFullPage/);
  assert.match(workspace, /workspaceNavigator\.setCollapsed\?\.\(!bothCollapsed\)/);
  assert.match(workspace, /fileCapabilityPanel\.setExpanded\?\.\(bothCollapsed\)/);
  assert.match(css, /\.file-capability-native-preview/);
  assert.doesNotMatch(source, /frame\.src = data\.dataUrl/);
});
