import assert from 'node:assert/strict';
import test from 'node:test';
import { removeClosedWindowFromAllLayouts, removeWindowLayoutMember, setWindowLayoutInstanceSuppressed } from './public/workspace-model-20260730b.js';
import { createWindowLayoutRetirementWriter } from './public/app/window-layout-workspace.js';
import { createWindowLayoutRecordingLifecycle as createOwner } from './public/app/window-layout-recording-lifecycle.js';
const ID='W0123456789abcdef';
const tick=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
function harness(){
 const calls=[];let readOnly=false;let widget=false;let persisted=true;let runtimeActive='A';const timers=new Map();let timerId=0;
 let state={activeWindowLayoutId:'A',windowLayouts:['A','B'].map(id=>({id,name:id,tracking:{enabled:true,suppressedInstanceIds:[]},arrangement:{version:2,members:[{id:'M',descriptor:{version:1,title:'Title',executableFingerprint:'a'.repeat(64),windowInstanceId:ID},state:'normal',bounds:null}]}}))};
 const runtime={capabilities:new Map([['A:M','a'],['B:M','b']]),icons:new Map([['A:M','i'],['B:M','j']]),saveTimer:null,pickAttempt:null,pickUnsubscribe:null};
 const store={commit:async next=>{calls.push(['commit']);if(persisted)state=next;return persisted;}};
 const controller={getSnapshot:()=>({activeLayoutId:runtimeActive}),reconcileActive:async()=>calls.push(['reconcile']),stop:async options=>calls.push(['stop',options])};
 const recording={resumeRecording:async id=>calls.push(['resume',id])};
 const writer=createWindowLayoutRetirementWriter({getState:()=>state,commitState:next=>store.commit(next),model:{removeWindowLayoutMember},capabilities:runtime.capabilities,icons:runtime.icons});
 const deps={get state(){return state;},getState:()=>state,get WIDGET_SURFACE(){return widget;},isWidgetSurface:()=>widget,windowLayoutWidgetClient:{sendCommand:command=>{calls.push(['widget-command',command]);return true;}},sendWidgetCommand:command=>{calls.push(['widget-command',command]);return true;},windowLayoutDetachment:{isReadOnly:()=>readOnly},windowLayoutRuntime:runtime,windowLayoutRuntimeController:controller,getController:()=>controller,windowLayoutRecording:recording,getRecording:()=>recording,windowLayoutRetirementWriter:writer,retirementWriter:writer,windowLayoutWidgetPreviewCapabilities:new Map([['A:M','preview'],['B:M','preview']]),windowLayoutMemberKey:(l,m)=>l+':'+m,removeClosedWindowFromAllLayouts,removeWindowLayoutMember,setWindowLayoutInstanceSuppressed,store,windowLayoutSelection:{repair:(...args)=>{calls.push(['repair',...args]);return true;},remove:(...args)=>{calls.push(['selection-remove',...args]);return true;}},syncWindowLayoutMemberSelection:id=>calls.push(['selection-sync',id]),setWindowLayoutStatus:(...args)=>calls.push(['status',...args]),noteWindowLayoutCommit:(...args)=>calls.push(['note',...args]),windowLayoutWidgetChannelWorkspace:{noteCommitted:(...args)=>calls.push(['note',...args])},windowLayoutMemberPreview:{cancel:()=>calls.push(['preview'])},windowLayoutFromState:id=>state.windowLayouts.find(l=>l.id===id),saveWorkspaceView:()=>calls.push(['save']),closeWindowLayoutPicker:()=>calls.push(['close-picker']),host:{pickWindowCancel:async()=>calls.push(['cancel'])},WINDOW_LAYOUT_SAVE_DEBOUNCE_MS:180,setTimeout:(fn,delay)=>{timers.set(++timerId,{fn,delay});return timerId;},clearTimeout:id=>timers.delete(id)};
 return {owner:createOwner(deps),deps,calls,runtime,controller,store,timers,getState:()=>state,setPersisted:x=>{persisted=x;},setReadOnly:x=>{readOnly=x;},setWidget:x=>{widget=x;},setActive:x=>{runtimeActive=x;}};
}
test('active context comes from runtime even when durable id differs',()=>{const h=harness();h.setActive('B');assert.equal(h.owner.active('A'),false);assert.equal(h.owner.active('B'),true);});
test('resume observes durable active id without activating or replaying arrangement',async()=>{const h=harness();await h.owner.resume();assert.deepEqual(h.calls,[['resume','A']]);h.getState().activeWindowLayoutId=null;await h.owner.resume();assert.equal(h.calls.length,1);});
test('save debounce retains one trailing timer',()=>{const h=harness();h.owner.queueSave();h.owner.queueSave();assert.equal(h.timers.size,1);const timer=[...h.timers.values()][0];assert.equal(timer.delay,180);timer.fn();assert.deepEqual(h.calls,[['save']]);});
test('stop clears save and listener synchronously and waits for native cancel and controller draining',async()=>{const h=harness();h.owner.queueSave();h.runtime.pickAttempt=Symbol();h.runtime.pickLayoutId='A';h.runtime.pickUnsubscribe=()=>h.calls.push(['unsubscribe']);let cancel,stop;h.deps.host.pickWindowCancel=()=>new Promise(done=>{cancel=done;});h.controller.stop=options=>{assert.deepEqual(options,{clearActive:false});return new Promise(done=>{stop=done;});};let ended=false;const pending=h.owner.stop().then(()=>{ended=true;});assert.equal(h.timers.size,0);assert.equal(h.runtime.pickUnsubscribe,null);assert.equal(h.runtime.pickAttempt,null);assert.equal(h.runtime.pickLayoutId,null);cancel();await tick();assert.equal(ended,false);stop();await pending;assert.equal(ended,true);});
test('idle stop avoids native cancel and retains durable active id',async()=>{const h=harness();await h.owner.stop();assert.equal(h.calls.some(x=>x[0]==='cancel'),false);assert.equal(h.getState().activeWindowLayoutId,'A');});
test('widget retirement routes one typed command without local writes',async()=>{const h=harness();h.setWidget(true);assert.equal(await h.owner.retireEverywhere({windowInstanceId:ID}),true);assert.deepEqual(h.calls.map(x=>x[0]),['widget-command']);assert.equal(h.getState().windowLayouts[0].arrangement.members.length,1);});
test('confirmed retirement removes exact window across layouts and repairs each cache and selection',async()=>{const h=harness();assert.equal(await h.owner.retireEverywhere({windowInstanceId:ID}),true);assert.equal(h.getState().windowLayouts.every(l=>l.arrangement.members.length===0),true);assert.equal(h.runtime.capabilities.size,0);assert.equal(h.deps.windowLayoutWidgetPreviewCapabilities.size,0);assert.equal(h.calls.filter(x=>x[0]==='commit').length,1);assert.equal(h.calls.filter(x=>x[0]==='repair').length,2);assert.equal(h.calls.filter(x=>x[0]==='reconcile').length,1);});
test('refused retirement persistence leaves caches, selection and preview intact',async()=>{const h=harness();h.setPersisted(false);assert.equal(await h.owner.retireEverywhere({windowInstanceId:ID}),false);assert.deepEqual(h.calls.map(x=>x[0]),['commit']);assert.equal(h.runtime.capabilities.size,2);});
test('read-only retirement and unlink are zero writes',async()=>{const h=harness();h.setReadOnly(true);assert.equal(await h.owner.retireEverywhere({windowInstanceId:ID}),false);h.owner.retireMember({layoutId:'A',memberId:'M'});h.owner.unlink('A','M');assert.deepEqual(h.calls,[]);});
test('unlink suppresses exact Auto identity and reconciles only active context',()=>{const h=harness();h.setActive('B');h.owner.unlink('A','M');assert.deepEqual(h.getState().windowLayouts[0].tracking.suppressedInstanceIds,[ID]);assert.equal(h.getState().windowLayouts[1].arrangement.members.length,1);assert.equal(h.runtime.capabilities.has('A:M'),false);assert.equal(h.runtime.capabilities.has('B:M'),true);assert.equal(h.calls.some(x=>x[0]==='reconcile'),false);});
test('stale retirement intent is a no-op',()=>{const h=harness();h.owner.retireMember({layoutId:'A',memberId:'absent'});assert.deepEqual(h.calls,[]);});
