import assert from 'node:assert/strict';
import test from 'node:test';
import { createWindowLayoutWidgetPicker as createPicker } from './public/app/window-layout-widget-picker.js';
const tick=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function harness(){
 const calls=[];const widgetState={snapshot:{members:[]},candidates:null,pickAttempt:null,pickUnsubscribe:null};const runtime={pickLayoutId:null};let dom=null;
 const host={windowCandidatePickerClose:async()=>calls.push(['close']),windowCandidates:async()=>({outcome:'success',candidates:[]}),windowCandidatePicker:async()=>({action:'dismiss'}),pickWindowCancel:async()=>calls.push(['cancel']),pickWindowBegin:async()=>({outcome:'started'}),onPickResult:fn=>{fn({outcome:'cancelled'});return ()=>calls.push(['unsubscribe']);}};
 const client={sendCommandAndWait:async(...args)=>{calls.push(['command',...args]);return {type:'success'};}};
 const deps={host,widgetState,windowLayoutRuntime:runtime,client,layoutId:'L',windowLayoutMemberPreview:{cancel:()=>calls.push(['preview'])},setWindowLayoutStatus:(...args)=>calls.push(['status',...args]),closeWindowLayoutCandidate:async(...args)=>calls.push(['close-candidate',...args]),restoreHoveredWindowLayoutPreview:id=>calls.push(['restore',id]),elements:{grid:{querySelector:()=>dom}},CSS:{escape:x=>x},crypto:{randomUUID:()=> 'P'},bindWindowLayoutPickerCandidate:async()=>({bound:{outcome:'missing',error:'expired'}}),escapeHtml:x=>x};
 return {picker:createPicker(deps),deps,host,client,widgetState,runtime,calls,setDom:x=>{dom=x;}};
}
test('idle close avoids native dismiss and clears presentation',async()=>{const h=harness();h.widgetState.candidates=[{}];await h.picker.close({requireClosed:true});assert.equal(h.widgetState.candidates,null);assert.deepEqual(h.calls,[['restore','L']]);});
test('visible chooser close invalidates immediately and required rejection propagates',async()=>{const h=harness();const dom={innerHTML:'rows'};h.setDom(dom);h.host.windowCandidatePickerClose=async()=>{throw Error('blocked');};await assert.rejects(h.picker.close({requireClosed:true}),/blocked/);assert.equal(dom.innerHTML,'');await h.picker.close();});
test('cancelled direct result sends no workspace mutation and cleans ownership',async()=>{const h=harness();await h.picker.direct();assert.equal(h.calls.some(x=>x[0]==='command'),false);assert.equal(h.widgetState.pickAttempt,null);assert.equal(h.widgetState.pickUnsubscribe,null);assert.equal(h.runtime.pickLayoutId,null);});
test('direct result buffered before begin settles commits through workspace with one stale retry',async()=>{const h=harness();let done;h.host.pickWindowBegin=()=>new Promise(resolve=>{done=resolve;});h.host.onPickResult=fn=>{fn({outcome:'committed',adds:[],removes:[]});done({outcome:'started'});return ()=>h.calls.push(['unsubscribe']);};let count=0;h.client.sendCommandAndWait=async(command,options)=>{h.calls.push(['command',command,options]);return {type:++count===1?'stale':'success'};};await h.picker.direct();assert.equal(count,2);assert.equal(h.calls.filter(x=>x[0]==='command')[0][2].timeoutMs,30000);assert.equal(h.widgetState.pickUnsubscribe,null);});
test('direct begin failure cleans buffered listener without commit',async()=>{const h=harness();h.host.pickWindowBegin=async()=>({outcome:'failed',error:'no picker'});await h.picker.direct();assert.equal(h.calls.some(x=>x[0]==='command'),false);assert.equal(h.calls.some(x=>x[0]==='status'&&x[2]==='no picker'),true);assert.equal(h.widgetState.pickUnsubscribe,null);});
test('chooser close failure prevents direct begin',async()=>{const h=harness();h.setDom({innerHTML:'rows'});h.host.windowCandidatePickerClose=async()=>{throw Error('blocked');};h.host.pickWindowBegin=()=>assert.fail('must not begin');await h.picker.direct();assert.equal(h.calls.some(x=>x[0]==='status'&&x[2]==='blocked'),true);});
test('superseded direct attempt cannot apply or clear successor ownership',async()=>{const h=harness();let done;h.host.pickWindowCancel=()=>new Promise(resolve=>{done=resolve;});const pending=h.picker.direct();await tick();const successor=Symbol('successor');h.widgetState.pickAttempt=successor;done();await pending;assert.equal(h.widgetState.pickAttempt,successor);assert.equal(h.calls.some(x=>x[0]==='command'),false);});
test('late list response cannot alter retired candidates or status',async()=>{const h=harness();let done;h.host.windowCandidates=()=>new Promise(resolve=>{done=resolve;});const pending=h.picker.open();await tick();await h.picker.close();done({outcome:'success',candidates:[{id:'late'}]});await pending;assert.equal(h.widgetState.candidates,null);assert.equal(h.calls.some(x=>x[0]==='status'),false);});
test('list binding keeps exact retained row and reports failure without workspace mutation',async()=>{const h=harness();const row={id:'old',title:'retained'};h.widgetState.candidates=[row];h.deps.bindWindowLayoutPickerCandidate=async(id,value)=>{assert.equal(id,'old');assert.equal(value,row);return {bound:{outcome:'missing',error:'expired'}};};h.picker=createPicker(h.deps);assert.equal(await h.picker.candidate('old'),false);assert.equal(h.calls.some(x=>x[0]==='command'),false);assert.equal(h.calls.at(-1)[2],'expired');});
test('missing list row is byte-zero no-op',async()=>{const h=harness();assert.equal(await h.picker.candidate('absent'),false);assert.deepEqual(h.calls,[]);});
