import assert from 'node:assert/strict';
import test from 'node:test';
import { createWindowLayoutWorkspacePicker as createPicker } from './public/app/window-layout-workspace-picker.js';
const tick=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
function harness(overrides={}){
 const calls=[];let readOnly=false;const runtime={pickerOpenFor:null,pickerGeneration:0,pickerCandidates:null,pickUnsubscribe:null};
 const host={pickWindowCancel:async()=>calls.push(['cancel']),pickWindowBegin:async()=>({outcome:'started'}),pickWindowCommit:async()=>calls.push(['commit']),onPickResult:fn=>{fn({outcome:'cancelled'});return ()=>calls.push(['unsubscribe']);},windowCandidatePickerClose:async()=>calls.push(['close']),windowCandidates:async()=>({outcome:'success',candidates:[]}),windowCandidatePicker:async()=>({action:'dismiss'})};
 const deps={host,windowLayoutRuntime:runtime,windowLayoutDetachment:{isReadOnly:()=>readOnly},windowLayoutMemberPreview:{cancel:()=>calls.push(['preview-cancel'])},windowLayoutFromState:()=>({arrangement:{members:[]}}),setWindowLayoutStatus:(...args)=>calls.push(['status',...args]),setWindowLayoutTransientStatus:(...args)=>calls.push(['transient',...args]),windowLayoutStatusForOutcome:value=>value,closeWindowLayoutCandidate:async()=>{},handleWindowLayoutPickCandidate:async()=>{},restoreHoveredWindowLayoutPreview:id=>calls.push(['restore-preview',id]),document:{querySelector:()=>null},CSS:{escape:value=>value},crypto:{randomUUID:()=> 'picker-id'},console:{info(){},error(){}},applyWindowLayoutPickSet:async(...args)=>calls.push(['apply',...args]),...overrides};
 const picker=createPicker(deps);return {picker,calls,runtime,host,deps,setReadOnly:value=>{readOnly=value;}};
}
test('required close propagates rejection; ordinary close swallows it and clears ownership',async()=>{const h=harness();h.host.windowCandidatePickerClose=async()=>{throw Error('close failed');};h.runtime.pickerOpenFor='L';await assert.rejects(h.picker.close({requireClosed:true}),/close failed/);assert.equal(h.runtime.pickerOpenFor,null);h.runtime.pickerOpenFor='L';await h.picker.close();assert.equal(h.runtime.pickerCandidates,null);});
test('direct cancel is zero durable application and cleans the listener/attempt',async()=>{const h=harness();await h.picker.direct('L');assert.equal(h.calls.some(c=>c[0]==='apply'),false);assert.equal(h.runtime.pickUnsubscribe,null);assert.equal(h.runtime.pickAttempt,null);assert.equal(h.runtime.pickLayoutId,null);});
test('committed result arriving before begin settles is applied once after listener cleanup',async()=>{const h=harness();let beginResolve;h.host.pickWindowBegin=()=>new Promise(done=>{beginResolve=done;});h.host.onPickResult=fn=>{fn({outcome:'committed',adds:[],removes:[]});beginResolve({outcome:'started'});return ()=>h.calls.push(['unsubscribe']);};await h.picker.direct('L');assert.equal(h.calls.filter(c=>c[0]==='apply').length,1);assert.equal(h.runtime.pickUnsubscribe,null);assert.equal(h.calls.at(-1)[0],'apply');});
test('failed begin removes listener and never applies the buffered result',async()=>{const h=harness();h.host.pickWindowBegin=async()=>({outcome:'failed',error:'unavailable'});await h.picker.direct('L');assert.equal(h.runtime.pickUnsubscribe,null);assert.equal(h.calls.some(c=>c[0]==='apply'),false);assert.equal(h.calls.some(c=>c[0]==='status'&&c[2]==='unavailable'),true);});
test('handoff during begin prevents status and durable application',async()=>{const h=harness();h.host.pickWindowBegin=async()=>{h.setReadOnly(true);return {outcome:'failed',error:'old'};};await h.picker.direct('L');assert.equal(h.calls.some(c=>['status','apply'].includes(c[0])),false);});
test('direct pick waits for chooser close and refuses close failure before starting host session',async()=>{const h=harness();h.runtime.pickerOpenFor='L';h.host.windowCandidatePickerClose=async()=>{throw Error('blocked');};h.host.pickWindowBegin=async()=>assert.fail('must not start');await h.picker.direct('L');assert.equal(h.calls.some(c=>c[0]==='status'&&c[2]==='blocked'),true);});
test('stale list rejection cannot overwrite a later picker generation',async()=>{const h=harness();let reject;h.host.windowCandidates=()=>new Promise((_done,fail)=>{reject=fail;});const pending=h.picker.open('L');await tick();h.picker.close();reject(Error('stale'));await pending;assert.equal(h.calls.some(c=>c[0]==='transient'),false);});
test('cancel returns host draining promise and releases result listener immediately',async()=>{const h=harness();let done;h.host.pickWindowCancel=()=>new Promise(resolve=>{done=resolve;});h.runtime.pickUnsubscribe=()=>h.calls.push(['unsubscribe']);const pending=h.picker.cancel();assert.equal(h.runtime.pickUnsubscribe,null);done();await pending;assert.deepEqual(h.calls,[['unsubscribe']]);});
test('active direct-pick keys confirm except Escape, which cancels and consumes the key',async()=>{const h=harness();let prevented=0;let stopped=0;h.runtime.pickUnsubscribe=()=>h.calls.push(['unsubscribe']);h.runtime.pickLayoutId='L';assert.equal(h.picker.keydown({key:'x',preventDefault(){prevented++;},stopPropagation(){stopped++;}}),true);await tick();assert.equal(h.calls.some(c=>c[0]==='commit'),true);assert.equal(prevented,1);assert.equal(stopped,1);h.calls.length=0;h.runtime.pickUnsubscribe=()=>h.calls.push(['unsubscribe']);assert.equal(h.picker.keydown({key:'Escape',preventDefault(){prevented++;},stopPropagation(){stopped++;}}),true);await tick();assert.equal(h.calls.some(c=>c[0]==='cancel'),true);assert.equal(h.calls.some(c=>c[0]==='commit'),false);});
test('Escape closes an open list picker and unrelated keys fall through',async()=>{const h=harness();h.runtime.pickerOpenFor='L';assert.equal(h.picker.keydown({key:'Escape',preventDefault(){},stopPropagation(){}}),true);await tick();assert.equal(h.runtime.pickerOpenFor,null);assert.equal(h.calls.some(c=>c[0]==='close'),true);assert.equal(h.picker.keydown({key:'a',preventDefault(){},stopPropagation(){}}),false);});
test('document click closes only when it lands outside the active picker',async()=>{const h=harness();h.runtime.pickerOpenFor='L';assert.equal(h.picker.documentClick({target:{closest:()=>({})}}),false);assert.equal(h.runtime.pickerOpenFor,'L');assert.equal(h.picker.documentClick({target:{closest:()=>null}}),true);await tick();assert.equal(h.runtime.pickerOpenFor,null);});
