import assert from 'node:assert/strict';
import test from 'node:test';
import { createWindowLayoutPreviewPresentation as createPresentation } from './public/app/window-layout-preview-presentation.js';
function harness(widget=false){
 const calls=[];const frames=new Map();const timers=new Map();let id=0;
 const name={textContent:''};const icon={hidden:true,removeAttribute:key=>{delete icon[key];}};const preview={replaceChildren:()=>calls.push(['clear-preview'])};
 const classes=new Set();const element={hidden:true,style:{},setAttribute(){},classList:{add:key=>classes.add(key),remove:key=>classes.delete(key)},getBoundingClientRect:()=>({width:80,height:50}),querySelector:selector=>selector==='[data-wl-popover-name]'?name:selector==='[data-wl-popover-icon]'?icon:selector==='[data-wl-popover-preview]'?preview:null};
 let count=0;const document={body:{appendChild:()=>calls.push(['append'])},createElement:()=>{count++;if(count===1)return element;return {innerHTML:'',querySelector(){return this.innerHTML.includes('window-layout-member-preview-image')?{src:'data:image/png;base64,abc',getAttribute:key=>key==='width'?'240':'135'}:null;}};}};
 const host=Object.fromEntries(['widgetPreviewShow','windowPreviewShow','widgetPreviewHide','windowPreviewHide'].map(method=>[method,async(...args)=>{calls.push([method,...args]);}]));
 const owner=createPresentation({document,window:{innerWidth:200,innerHeight:150,screenX:100,screenY:200},host,WIDGET_SURFACE:widget,requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),windowLayoutMemberPreview:{schedule:(...args)=>calls.push(['schedule',...args])}});
 return {owner,calls,element,name,icon,classes,frames,timers,flush:()=>{const pending=[...timers.values()];timers.clear();for(const {fn}of pending)fn();}};
}
const anchor={left:5,top:20,bottom:30,width:10,height:10};
test('attached name/icon popover is reused and viewport clamped; animation makes it visible',()=>{const h=harness();h.owner.popover.show('A',anchor,'icon');assert.equal(h.name.textContent,'A');assert.equal(h.icon.src,'icon');assert.equal(h.element.style.left,'6px');assert.equal(h.element.style.top,'36px');for(const fn of h.frames.values())fn();assert.equal(h.classes.has('is-visible'),true);h.owner.popover.show('B',anchor);assert.equal(h.calls.filter(c=>c[0]==='append').length,1);assert.equal(h.icon.hidden,true);});
test('hide cancels animation and routes the existing workspace native hide',()=>{const h=harness();h.owner.popover.show('A',anchor);h.owner.popover.hide();assert.equal(h.frames.size,0);assert.equal(h.element.hidden,true);assert.equal(h.calls.at(-1)[0],'windowPreviewHide');});
test('widget retains name/anchor without displaying local popover and routes widget preview',()=>{const h=harness(true);h.owner.popover.show('A',anchor);assert.equal(h.calls.length,0);h.owner.popover.updatePreview('a','<img class="window-layout-member-preview-image">');assert.deepEqual(h.calls.at(-1),['widgetPreviewShow','data:image/png;base64,abc','A',240,135,{x:105,y:220,width:10,height:10}]);});
test('attached preview uses workspace authorization and clear routes hide',()=>{const h=harness();h.owner.popover.show('A',anchor);h.owner.popover.updatePreview('a','<img class="window-layout-member-preview-image">');assert.equal(h.calls.at(-1)[0],'windowPreviewShow');h.owner.popover.updatePreview('a',null);assert.equal(h.calls.at(-1)[0],'windowPreviewHide');});
test('dwell is 100ms, coalesces intents, and schedules the exact hovered member',()=>{const h=harness();const member={dataset:{wlLayout:'L',wlMember:'a'},isConnected:true,title:'A',getAttribute:()=>null,querySelector:()=>null,getBoundingClientRect:()=>anchor,matches:()=>true};h.owner.schedule(member);h.owner.schedule(member);assert.equal(h.timers.size,1);assert.equal([...h.timers.values()][0].ms,100);h.flush();assert.deepEqual(h.calls.at(-1),['schedule','L','a']);});
for(const gate of ['disconnected','not-hovered'])test(`dwell cancels presentation for ${gate}`,()=>{const h=harness();const member={dataset:{wlLayout:'L',wlMember:'a'},isConnected:gate!=='disconnected',getAttribute:()=>null,querySelector:()=>null,getBoundingClientRect:()=>anchor,matches:()=>gate!=='not-hovered'};h.owner.schedule(member);h.flush();assert.deepEqual(h.calls,[]);});
test('explicit dwell cancellation discards its timer',()=>{const h=harness();h.owner.schedule({dataset:{wlLayout:'L',wlMember:'a'},getAttribute:()=>null,querySelector:()=>null,getBoundingClientRect:()=>anchor});h.owner.cancel();assert.equal(h.timers.size,0);});
