import assert from 'node:assert/strict';
import test from 'node:test';
import { createWindowLayoutTrackingLifecycle as createTracking } from './public/app/window-layout-tracking-lifecycle.js';
const tick=async()=>{for(let i=0;i<24;i++)await Promise.resolve();};
const ID='W0123456789abcdef';
function harness(){
 const calls=[];let state={windowLayouts:[{id:'L',tracking:{enabled:true},arrangement:{members:[{id:'M',descriptor:{windowInstanceId:ID}}]}}]};let now=1000;let role='writer';let readOnly=false;const timers=new Map();let timerId=0;
 const auto={addFromEvent:async event=>{calls.push(['add',event]);return {outcome:'added'};},acceptBaseline:async(_s,reconcile)=>({events:await reconcile()?[]:[]})};
 const host={resolveWindowInstance:async()=>({outcome:'missing'}),windowLifecycleSnapshot:async()=>({snapshot:{complete:true,trackerSessionId:'session',windows:[]}}),windowCandidates:async()=>({outcome:'success',candidates:[]}),bindWindowCandidate:async()=>({outcome:'missing'}),observeWindowCapability:async()=>({outcome:'missing'}),onWindowLifecycleEvent:fn=>{host.event=fn;},onWindowLifecycleBaseline:fn=>{host.baseline=fn;}};
 const deps={get state(){return state;},getState:()=>state,get surfaceCoordinator(){return {role};},getSurfaceCoordinator:()=>({role}),host,windowLayoutDetachment:{isReadOnly:()=>readOnly,isStopped:()=>false},hasDocumentWriteAuthority:()=>!readOnly,SURFACE_ROLE:{WRITER:'writer'},windowLayoutGoneConfirmations:new Map(),createWindowLayoutAutoTracking:()=>auto,windowLayoutRuntime:{capabilities:new Map(),icons:new Map()},windowLayoutWidgetPreviewCapabilities:new Map(),windowLayoutRuntimeController:{reconcileActive:async()=>calls.push(['reconcile-active'])},windowLayoutRecording:{ensureRecording:async()=>calls.push(['record'])},isActiveRecordingContext:()=>false,windowLayoutMemberKey:(l,m)=>l+':'+m,store:{commit:async next=>{calls.push(['commit']);state=next;return true;}},saveWorkspaceView:()=>calls.push(['save']),noteWindowLayoutCommit:(...args)=>calls.push(['note',...args]),retireClosedWindowEverywhere:async(...args)=>{calls.push(['retire',...args]);return true;},windowLayoutSelection:{repair:()=>false},syncWindowLayoutMemberSelection:()=>{},setWindowLayoutStatus:(...args)=>calls.push(['status',...args]),windowLayoutMemberPreview:{cancel:()=>calls.push(['preview'])},reconcileWindowLayoutsAfterStartup:s=>s,windowLayoutFromState:id=>state.windowLayouts.find(l=>l.id===id),windowLayoutStatusForOutcome:x=>x,addWindowLayoutMember:(s,l,m)=>({...s,windowLayouts:s.windowLayouts.map(x=>x.id===l?{...x,arrangement:{members:[...x.arrangement.members,m]}}:x)}),setWindowLayoutTracking:(s,l,on)=>({...s,windowLayouts:s.windowLayouts.map(x=>x.id===l?{...x,tracking:{enabled:on}}:x)}),crypto:{randomUUID:()=> 'new'},window:{setTimeout:fn=>{timers.set(++timerId,fn);return timerId;},clearTimeout:id=>timers.delete(id)},Date:{now:()=>now}};
 const owner=createTracking(deps);return {owner,deps,host,auto,calls,timers,setNow:x=>{now=x;},setRole:x=>{role=x;},setReadOnly:x=>{readOnly=x;},getState:()=>state};
}
test('two missing sweeps are required to retire a saved identity',async()=>{const h=harness();await h.owner.reconcile();assert.equal(h.calls.some(x=>x[0]==='retire'),false);await h.owner.reconcile();assert.equal(h.calls.filter(x=>x[0]==='retire').length,1);});
test('resolver outage breaks confirmation and never retires',async()=>{const h=harness();await h.owner.reconcile();h.host.resolveWindowInstance=async()=>{throw Error('offline');};await h.owner.reconcile();h.host.resolveWindowInstance=async()=>({outcome:'missing'});await h.owner.reconcile();assert.equal(h.calls.some(x=>x[0]==='retire'),false);});
test('complete live snapshot clears a prior missing observation',async()=>{const h=harness();await h.owner.reconcile();h.host.windowLifecycleSnapshot=async()=>({snapshot:{complete:true,windows:[{windowInstanceId:ID}]}});await h.owner.reconcile();h.host.windowLifecycleSnapshot=async()=>({snapshot:{complete:true,windows:[]}});await h.owner.reconcile();assert.equal(h.calls.some(x=>x[0]==='retire'),false);});
test('lifecycle gone corroborates with exact resolver before removal',async()=>{const h=harness();await h.owner.process({kind:'gone',windowInstanceId:ID});assert.equal(h.calls.filter(x=>x[0]==='retire').length,1);});
test('transient lifecycle gone never retires a live exact identity',async()=>{const h=harness();h.host.resolveWindowInstance=async()=>({outcome:'success'});await h.owner.process({kind:'gone',windowInstanceId:ID});assert.equal(h.calls.some(x=>x[0]==='retire'),false);});
test('writer loss while awaiting exact close proof blocks removal',async()=>{const h=harness();h.host.resolveWindowInstance=async()=>{h.setRole('reader');return {outcome:'missing'};};await h.owner.process({kind:'gone',windowInstanceId:ID});assert.equal(h.calls.some(x=>x[0]==='retire'),false);});
test('event drain continues after a failed open',async()=>{const h=harness();let count=0;h.auto.addFromEvent=async()=>{if(++count===1)throw Error('transient');return {outcome:'added'};};h.host.event({kind:'open',windowInstanceId:ID,trackerSessionId:'session',sequence:1});h.host.event({kind:'open',windowInstanceId:'Wfedcba9876543210',trackerSessionId:'session',sequence:2});await tick();assert.equal(count,2);});
test('failed opens retry only after cadence and expire after sixty seconds',async()=>{const h=harness();h.auto.addFromEvent=async event=>{h.calls.push(['add',event]);return {outcome:'missing'};};await h.owner.process({kind:'open',windowInstanceId:ID});h.setNow(2000);await h.owner.reconcile();assert.equal(h.calls.filter(x=>x[0]==='add').length,1);h.setNow(3100);await h.owner.reconcile();assert.equal(h.calls.filter(x=>x[0]==='add').length,2);h.setNow(62000);await h.owner.reconcile();assert.equal(h.calls.filter(x=>x[0]==='add').length,2);});
test('read-only surface performs no tracking or snapshot work',async()=>{const h=harness();h.setReadOnly(true);await h.owner.process({kind:'open',windowInstanceId:ID});await h.owner.reconcile();await h.owner.baseline();assert.deepEqual(h.calls,[]);});
test('reconcile scheduling is idempotent and stop clears its timer',()=>{const h=harness();h.owner.schedule();h.owner.schedule();assert.equal(h.timers.size,1);h.owner.stop();assert.equal(h.timers.size,0);});
test('failed population releases its lock for a later attempt',async()=>{const h=harness();let count=0;h.host.windowCandidates=async()=>{count++;throw Error('offline');};await h.owner.populate('L');await h.owner.populate('L');assert.equal(count,2);assert.equal(h.calls.filter(x=>x[0]==='status').length,2);});
test('disabling Auto persists once and retains members without starting population',async()=>{const h=harness();assert.equal(await h.owner.toggle('L'),true);assert.equal(h.getState().windowLayouts[0].tracking.enabled,false);assert.equal(h.getState().windowLayouts[0].arrangement.members.length,1);assert.deepEqual(h.calls.map(x=>x[0]),['commit','save','note']);});

test('refused startup commit leaves the baseline retryable',async()=>{const h=harness();let attempts=0;h.deps.reconcileWindowLayoutsAfterStartup=state=>({...state,activeWindowLayoutId:null});h.deps.store.commit=async()=>{attempts++;return false;};h.owner=createTracking(h.deps);await h.owner.baseline();await h.owner.baseline();assert.equal(attempts,2);assert.equal(h.calls.some(x=>x[0]==='save'),false);});
test('successful startup reconciliation runs once across later watcher baselines',async()=>{const h=harness();let attempts=0;h.deps.reconcileWindowLayoutsAfterStartup=state=>{attempts++;return {...state};};h.owner=createTracking(h.deps);await h.owner.baseline();await h.owner.baseline();assert.equal(attempts,1);assert.equal(h.calls.filter(x=>x[0]==='save').length,1);});
test('population rechecks suppression after awaited observation',async()=>{const h=harness();const id='Wfedcba9876543210';h.host.windowCandidates=async()=>({outcome:'success',candidates:[{id:'C',windowInstanceId:id}]});h.host.bindWindowCandidate=async()=>({outcome:'success',capability:'cap',descriptor:{windowInstanceId:id}});h.host.observeWindowCapability=async()=>{h.getState().windowLayouts[0].tracking.suppressedInstanceIds=[id];return {outcome:'success',observation:{state:'normal'}};};await h.owner.populate('L');assert.equal(h.calls.some(x=>x[0]==='commit'),false);assert.equal(h.getState().windowLayouts[0].arrangement.members.length,1);});
test('population commits then retains capability and refreshes recording once',async()=>{const h=harness();const id='Wfedcba9876543210';h.host.windowCandidates=async()=>({outcome:'success',candidates:[{id:'C',windowInstanceId:id}]});h.host.bindWindowCandidate=async()=>({outcome:'success',capability:'cap',descriptor:{windowInstanceId:id}});h.host.observeWindowCapability=async()=>({outcome:'success',observation:{state:'minimized',bounds:{x:3}}});await h.owner.populate('L');assert.deepEqual(h.calls.map(x=>x[0]),['commit','save','note','record']);assert.equal(h.deps.windowLayoutRuntime.capabilities.get('L:new'),'cap');assert.equal(h.getState().windowLayouts[0].arrangement.members.at(-1).state,'minimized');});
