// Rebuilds public/vendor/d3/ from node_modules.
//
// Why this exists: the previous vendor files were standalone bundles, each with
// its own inlined copy of d3-selection. d3-zoom/d3-transition/d3-drag install
// .transition()/.interrupt()/.drag() onto *their* private selection prototype,
// so the app -- importing select() from a different file -- got selections
// missing those methods, and any d3-zoom call touching a selection threw.
//
// The fix is a shared module graph. We copy each d3 package's ESM source
// verbatim and only rewrite bare specifiers ("d3-selection") into relative
// paths ("../d3-selection/src/index.js"). No identifier rewriting, no
// concatenation -- so there is exactly one d3-selection module instance and the
// prototype patches are visible everywhere.
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync, statSync } from 'node:fs';
import { dirname, resolve, relative, join } from 'node:path';

const ROOT = process.argv[2];
const NM = resolve(ROOT, 'node_modules');
const OUT = resolve(ROOT, 'public/vendor/d3');

// Every package reachable from the entry points below.
const PACKAGES = [
  'd3-selection', 'd3-transition', 'd3-zoom', 'd3-force', 'd3-drag',
  'd3-dispatch', 'd3-interpolate', 'd3-color', 'd3-ease', 'd3-timer',
  'd3-quadtree',
];

// Matches the specifier in any import/export ... from "..." plus bare
// side-effect imports (import "d3-selection";).
const SPEC_RE = /((?:^|\n)\s*(?:import|export)(?:[\s\S]*?\sfrom)?\s*)(["'])([^"']+)\2/g;

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else if (name.endsWith('.js')) out.push(full);
  }
  return out;
}

rmSync(OUT, { recursive: true, force: true });

const versions = [];
let fileCount = 0;

for (const pkg of PACKAGES) {
  const pkgJson = JSON.parse(readFileSync(resolve(NM, pkg, 'package.json'), 'utf8'));
  versions.push(`${pkg}@${pkgJson.version}`);

  const srcDir = resolve(NM, pkg, 'src');
  for (const file of walk(srcDir)) {
    const code = readFileSync(file, 'utf8');
    const destFile = resolve(OUT, pkg, 'src', relative(srcDir, file));

    const rewritten = code.replace(SPEC_RE, (match, head, quote, spec) => {
      if (spec.startsWith('.')) return match; // intra-package: already relative
      if (!PACKAGES.includes(spec)) throw new Error(`unvendored dependency "${spec}" in ${file}`);
      let rel = relative(dirname(destFile), resolve(OUT, spec, 'src/index.js')).replace(/\\/g, '/');
      if (!rel.startsWith('.')) rel = `./${rel}`;
      return `${head}${quote}${rel}${quote}`;
    });

    mkdirSync(dirname(destFile), { recursive: true });
    writeFileSync(destFile, rewritten);
    fileCount += 1;
  }
}

// Entry points the app imports. Each just re-exports a package's index, so
// call sites keep using './vendor/d3-zoom.js' etc.
const ENTRIES = {
  'd3-selection.js': 'd3-selection',
  'd3-zoom.js': 'd3-zoom',
  'd3-force.js': 'd3-force',
  'd3-transition.js': 'd3-transition',
};

for (const [entry, pkg] of Object.entries(ENTRIES)) {
  writeFileSync(
    resolve(ROOT, 'public/vendor', entry),
    `// Vendored ${pkg} -- see public/vendor/d3/ and tools/vendor-d3.mjs.\n` +
    `// Do not edit by hand; run \`npm run vendor:d3\` to regenerate.\n` +
    `export * from './d3/${pkg}/src/index.js';\n`,
  );
}

writeFileSync(
  resolve(OUT, 'README.md'),
  `# Vendored d3\n\nGenerated by \`tools/vendor-d3.mjs\` -- do not edit by hand.\n\n` +
  `Sources copied verbatim from node_modules; only bare import specifiers were\n` +
  `rewritten to relative paths so every package shares ONE d3-selection module\n` +
  `instance. That sharing is load-bearing: d3-transition and d3-drag patch\n` +
  `\`selection.prototype\` (.transition/.interrupt/.drag), and those patches are\n` +
  `only visible to the app if it imports the same module instance.\n\n` +
  `Versions:\n\n${versions.map(v => `- ${v}`).join('\n')}\n`,
);

console.log(`vendored ${fileCount} files from ${PACKAGES.length} packages`);
console.log(versions.join('\n'));
